name: craft4-ci
on:
  workflow_dispatch:
  push:
    branches:
      - '7.x'
  pull_request:
permissions:
  contents: read
concurrency:
  group: craft4-ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  code-quality:
    name: code-quality (Craft 4)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:2.7
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
      - name: Install Craft 4 dependencies
        run: composer update --no-interaction --no-audit --no-progress --prefer-dist --with craftcms/cms:^4 --with-all-dependencies
      - name: Run ECS
        run: composer check-cs
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --configuration=phpstan.craft4.neon --memory-limit=1G
      - name: Install Node dependencies
        run: npm ci
      - name: Run Prettier
        run: npm run check-prettier
      - name: Run Tests
        run: composer run testunit
